### ISSUE TITLE
Issue with "starting kernel" 

### ISSUE THREAD

**Issue by FelipeAlvaro** [gisab/WDMC-Ex2#1]
Can be deleted! Issue was about the wrong partition

**Comment by FelipeAlvaro** [comment]
Hi Gisap, I thought I come further with not using a new disk, but even after setting up the raid 1 set-up I get the same issue. I can follow the full instruction until the starting kernel comes - then I get a kernel panic with '
No filesystem could mount root, tried:
 ext3
 ext2
 ext4
 vfat
 msdos
 iso9660

Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(1,0)'

Can you help me further?

**Comment by gisab** [comment]
Hi Felipe.
You need to follow this procedure https://github.com/gisab/WDMC-Ex2/blob/main/2.UBoot/README.md 
and in particular, you need to tell UBoot where the root partition is, via the command:
`bootargs=root=/dev/ram (replacing /dev/ram with the device containing the root image, for example /dev/sda1)`

**Comment by FelipeAlvaro** [comment]
Sorry for double checking, but did you completely set up a new partition next to the existing ones (and in line with the prev. partition of WS itself) on the harddrives?

**Comment by gisab** [comment]
Hi again Felipe.
Sorry, but I don't know what you are doing and so to give you detailed support.
You have the freedon to partition the disk as you like.
You need at minimum:
- one ext2 partition for loading the kernel files; alternatively, you load the kernel image via tftp; this partition shall be configured in uboot with the instruction to load the kernel;
- one ext4 with the linux root partition; this partition shall be passed as bootargs to the kernel itself
